name: Test

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
    - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 18.x
    steps:
      - name: CHECKOUT GIT REPOSIRORY
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
            version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies (pnpm)
        run: pnpm install
      - name: Running tests
        run: pnpm t -- --passWithNoTests
      - name: Upload coverage data to codacy
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: report/coverage/cobertura-coverage.xml
